FROM python:3.12.2-alpine3.18

RUN mkdir /app

WORKDIR /app

RUN pip install --upgrade pip

COPY ./DockerFiles/requirements.txt .

RUN pip install -r requirements.txt

COPY ./pfwebsite /app/pfwebsite

RUN mkdir /app/data

EXPOSE 8080

CMD [ "python","/app/pfwebsite/manage.py","runserver","0.0.0.0:8080" ]